### ISSUE TITLE
getTestGuid should include test path along with test name

### ISSUE THREAD

**Issue by serkan-inci** [karanjitsingh/jstestcontext#5]
Otherwise, there will be collision between a.test.js and b.test.js since the name of the first test will be 'spec0' for both of them.

**Comment by karanjitsingh** [comment]
![image](https://user-images.githubusercontent.com/4632805/52779602-80fb4f00-306e-11e9-95ed-428012b2469a.png)

The spec object for jasmine/jest does not provide a filename, so best solution would be to concat the full name of the spec with the spec id.
