### ISSUE TITLE
getTestAttachmentDirectory fails due to "strict mode"

### ISSUE THREAD

**Issue by serkan-inci** [karanjitsingh/jstestcontext#6]
Call fails with below message when trying to access getCurrentTestName.caller:

`'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"`

**Comment by karanjitsingh** [comment]
@serkan-inci, btw TestContext will not work with file in "strict mode" so we'll have to add the option `noImplicitStrict` to the tsconfig of l2 tests
